### ISSUE TITLE
SearchSeries liefert mehr Sprachen auch wenn auf Sprachen gefiltert wurde

### ISSUE THREAD

**Issue by sbetzin** [ViktorHofer/TheTVDBSharp#1]
var results = await tvdb.SearchSeries("Checker Can", Language.Deutsch);

enthält 2 Einträge, einmal auf Deutsch, einmal auf Englisch.

Erwarten würde ich nur den deutschen Eintrag, da ich die Sprache Deutsch in der Suche angegeben habe

**Comment by ViktorHofer** [comment]
The SearchSeries member always contains an English result because this is by design by the TheTVDB Api. Of course you could argue that the library should filter it out, but there is a reason why the English result is always included.

**Comment by sbetzin** [comment]
Hi yes I understand. But in Terms of "principle of least astonishment" I would exspect the lib to filter it out. There could be an additional overload with boolean flag to include the english results anyway/as fallback.
